SETTING_ID_TO_NAME: dict[int, str] = {
    2:   "Video Resolution",
    3:   "Frames Per Second",
    5:   "Video Timelapse Rate",
    30:  "Photo Timelapse Rate",
    32:  "Nightlapse Rate",
    43:  "Webcam Digital Lenses",
    59:  "Auto Power Down",
    83:  "GPS",
    88:  "LCD Brightness",
    91:  "LED",
    108: "Video Aspect Ratio",
    121: "Video Lens",
    122: "Photo Lens",
    123: "Time Lapse Digital Lenses",
    125: "Photo Output",
    128: "Media Format",
    134: "Anti-Flicker",
    135: "Hypersmooth",
    150: "Video Horizon Leveling",
    151: "Photo Horizon Leveling",
    156: "Video Duration",
    157: "Multi Shot Duration",
    162: "Max Lens",
    167: "HindSight",
    168: "Scheduled Capture",
    171: "Photo Single Interval",
    172: "Photo Interval Duration",
    173: "Video Performance Mode",
    175: "Control Mode",
    176: "Easy Mode Speed",
    177: "Enable Night Photo",
    178: "Wireless Band",
    179: "Star Trails Length",
    180: "System Video Mode",
    182: "Video Bit Rate",
    183: "Bit Depth",
    184: "Profiles",
    186: "Video Easy Mode",
    187: "Lapse Mode",
    189: "Max Lens Mod",
    190: "Max Lens Mod Enable",
    191: "Easy Night Photo",
    192: "Multi Shot Aspect Ratio",
    193: "Framing",
    194: "Camera Mode",
    196: "360 Photo Files Extension",
    216: "Beep Volume",
    219: "Setup Screen Saver",
    223: "Setup Language",
    227: "Photo Mode",
    232: "Video Framing",
    233: "Multi Shot Framing",
    234: "Frame Rate",
    236: "Automatic Wi-Fi Access Point",
}
