STATUS_ID_TO_NAME: dict[int, str] = {
    1: "Battery Present",
    2: "Internal Battery Bars",
    6: "Overheating",
    8: "Busy",
    9: "Quick Capture",
    10: "Encoding",
    11: "LCD Lock",
    79: "FTU",
    81: "5GHz Available",
    82: "Ready",
    83: "OTA Charged",
    93: "Video Preset",
    94: "Photo Preset",
    95: "Timelapse Preset",
    96: "Preset Group",
    97: "Preset",
    98: "Preset Modified",
    99: "Remaining Live Bursts",
    100: "Live Bursts",
    101: "Capture Delay Active",
    102: "Media Mod State",
    103: "Time Warp Speed",
    104: "Linux Core",
    105: "Lens Type",
    106: "Hindsight",
    107: "Scheduled Capture Preset ID",
    108: "Scheduled Capture",
    110: "Display Mod Status",
    111: "SD Card Write Speed Error",
    112: "SD Card Errors",
    113: "Turbo Transfer",
    114: "Camera Control ID",
    115: "USB Connected",
    116: "USB Controlled",
    117: "SD Card Capacity",
    118: "Photo Interval Capture Count",
    122: "Camera Name",
}